### ISSUE TITLE
Allow resolving from `modules.ceylon-lang.org` during upload

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-herd#196]
Same as from Maven Central, but for Ceylon. Very useful in tests.

**Comment by lukedegruchy** [comment]
In addition to the pull request, I've written code to ensure that in the module/version page, the dependency will show with a link to modules.ceylon.herd and the text "Herd module" on the left hand side, but I haven't committed it yet.   In order to make this work, I needed to run the following alter table as JPA doesn't do this automatically:

alter table dependency add column resolvedfromherd boolean NOT NULL default false;

I'm not sure if there's a more elegant way to do this in JPA, given my lack of experience with that framework.

Another thing I'm not clear on is what the expected behaviour is for resolved dependencies from upload to upload, and how it works with the feature in Maven (it's not obvious to me how to test this with a maven dependency).

1) Force the user to re-resolve the module with each upload
2) Carry over the resolution from the previous upload.

I suspect it's 2), but I'm still stumped on how to do it.

**Comment by quintesse** [comment]
@lukedegruchy Changes to the database schema have to be done in the `db/db-XX.sql` and `db/update-XX.sql` files. Se also the README in the `db` folder. Updates are not done automatically, they have to be applied manually.

**Comment by quintesse** [comment]
Btw, I think option `1` is good enough for now, it's not as if this is really a great burden for the user.

**Comment by FroMage** [comment]
Yes, option 1 is good enough for now ;)
